services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ezyshop-sql
    environment:
      - SA_PASSWORD=SeninParolan123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: WebUI/Dockerfile
    container_name: ezyshop-web
    ports:
      - "7104:8080"
    depends_on:
      - sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  sqlvolume:
